server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/redo_laptopshop"
    username: root
    password: vanlong1606
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


# #spring.jpa.show-sql: true

# #config view engine
# # spring.mvc.view.prefix=/WEB-INF/view/
# # spring.mvc.view.suffix=.jsp
# #default = 1MB
# spring.servlet.multipart.max-file-size=50MB
# #default = 10 MB (form data)
# spring.servlet.multipart.max-request-size=50MB

# #config session
# spring.session.store-type=jdbc
# spring.session.timeout=30m
# spring.session.jdbc.initialize-schema=always
#server.servlet.session.timeout
#spring.session.jdbc.table-name=SPRING_SESSION
